export const FETCH_ERROR = 'FETCH_ERROR'
export const FETCH_LOADING = 'FETCH_LOADING'
export const FETCH_ERROR_CLEAR = 'FETCH_ERROR_CLEAR'

export const SET_VIEW_DESKTOP = 'SET_VIEW_DESKTOP'
export const SET_VIEW_LAPTOP = 'SET_VIEW_LAPTOP'
export const SET_VIEW_TABLET = 'SET_VIEW_TABLET'
export const SET_VIEW_IPHONE = 'SET_VIEW_IPHONE'
export const SET_VIEW_MOBILE = 'SET_VIEW_MOBILE'
